export const GET_POPULAR_DESTINATIONS = "GET_POPULAR_DESTINATIONS";
export const GET_VITAMIN_SEA = "GET_VITAMIN_SEA";
export const GET_DESTINATIONS = "GET_DESTINATIONS";
export const GET_NAIK_GUNUNG = "GET_NAIK_GUNUNG";
export const GET_NATURE = "GET_NATURE";

export const GET_BANK = "GET_BANK";

export const GET_TRIP = "GET_TRIP";

export const GET_CATEGORY = "GET_CATEGORY";
