export const GET_POPULAR_DESTINATIONS = "GET_POPULAR_DESTINATIONS";
export const GET_VITAMIN_SEA = "GET_VITAMIN_SEA";
export const GET_DESTINATIONS = "GET_DESTINATIONS";
export const GET_NAIK_GUNUNG = "GET_NAIK_GUNUNG";
export const GET_NATURE = "GET_NATURE";

// export const GET_POPULAR_MOVIES = "GET_MOVIES";
// export const GET_TOP_MOVIES = "GET_TOP_MOVIES";
// export const GET_MOVIE = "GET_MOVIE";
// export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
// export const GET_MOVIE_REVIEWS = "GET_MOVIE_REVIEWS";
